# Generated by Django 3.2.11 on 2022-01-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='配置名称')),
                ('value', models.CharField(max_length=256, verbose_name='配置值')),
            ],
            options={
                'verbose_name': '工作节点配置中心',
                'verbose_name_plural': '工作节点配置中心',
                'db_table': 'config',
            },
        ),
    ]
